### ISSUE TITLE
allDocs: include_docs: true is not default per docs

### ISSUE THREAD

**Issue by rjharmon** [jo/backbone-pouch#35]
I needed to specify options.allDocs.include_docs: true in order for a collection to actually fetch the document details.  That's contrary to my understanding of the docs, which indicate that include_docs should already default to true.

```
var Todo = Backbone.Model.extend({
  sync: BackbonePouch.sync({
    db: todoDb
  }),
});
Todo.prototype.idAttribute = "_id";
var TodoCollection = Backbone.Collection.extend({
  model: Todo,
  parse: function(result) {
    return _.pluck(result.rows, 'doc');
  },
  sync: BackbonePouch.sync({
    db: todoDb,
    options: {
      allDocs: {
        include_docs: true
        # ^^^^^^^^^^^^^^^^ doesn't include docs without this setting
      }
    }
  })
});
var todos = new TodoCollection();
todos.fetch();
```

**Comment by jo** [comment]
I prefer to stay with [PouchDBs defaults](http://pouchdb.com/api.html#batch_fetch) and try to introduce as less logic as possible.
